Repository yejin-kingdom/value-together, pull requests merged in 2023-12, with the labels that each got.

#3 build-check workflow 추가
  .github/workflows/check.yml
  .gitignore
Labels: docs

#4 cicd 추가
  .github/workflows/gradle.yml
  infra/Dockerfile
Labels: feat, docs

#7 sample api 추가
  build.gradle
  src/main/java/com/vt/valuetogether/domain/sample/controller/SampleController.java
  src/main/java/com/vt/valuetogether/domain/sample/dto/request/SampleSaveReq.java
  src/main/java/com/vt/valuetogether/domain/sample/dto/response/SampleGetRes.java
  src/main/java/com/vt/valuetogether/domain/sample/dto/response/SampleGetResList.java
  src/main/java/com/vt/valuetogether/domain/sample/dto/response/SampleSaveRes.java
  src/main/java/com/vt/valuetogether/domain/sample/entity/SampleEntity.java
  src/main/java/com/vt/valuetogether/domain/sample/repository/SampleRepository.java
  src/main/java/com/vt/valuetogether/domain/sample/servce/SampleService.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/response/RestResponse.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feat

#11 Remove : remove ValueTogetherApplicationTests.java
  src/test/java/com/vt/valuetogether/ValueTogetherApplicationTests.java
Labels: fix

#12 restdocs 추가
  .github/workflows/check.yml
  .github/workflows/gradle.yml
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/sample/dto/response/SampleSaveRes.java
  src/main/java/com/vt/valuetogether/domain/sample/servce/SampleService.java
  src/test/java/com/vt/valuetogether/domain/BaseMvcTest.java
  src/test/java/com/vt/valuetogether/domain/sample/controller/SampleControllerTest.java
Labels: feat, docs

#14 S3 configuration 추가
  build.gradle
  src/main/java/com/vt/valuetogether/global/s3/S3Config.java
  src/main/resources/application.yml
Labels: feat

#16 [#15] 회원가입 기능 추가
  build.gradle
  src/main/java/com/vt/valuetogether/domain/user/controller/UserController.java
  src/main/java/com/vt/valuetogether/domain/user/dto/request/UserSignupReq.java
  src/main/java/com/vt/valuetogether/domain/user/dto/response/UserSignupRes.java
  src/main/java/com/vt/valuetogether/domain/user/entity/Role.java
  src/main/java/com/vt/valuetogether/domain/user/entity/User.java
  src/main/java/com/vt/valuetogether/domain/user/repository/UserRepository.java
  src/main/java/com/vt/valuetogether/domain/user/service/UserService.java
  src/main/java/com/vt/valuetogether/domain/user/service/UserServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/vt/valuetogether/global/config/WebSecurityConfig.java
  src/main/java/com/vt/valuetogether/global/validator/UserValidator.java
  src/main/resources/application.yml
  src/test/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/UserTest.java
Labels: feat, test

#20 restdocs 배포 방식 변경
  .github/workflows/gradle.yml
Labels: feat, docs

#28 checklist 저장 api 추가
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/checklist/controller/ChecklistController.java
  src/main/java/com/vt/valuetogether/domain/checklist/dto/request/ChecklistSaveReq.java
  src/main/java/com/vt/valuetogether/domain/checklist/dto/response/ChecklistSaveRes.java
  src/main/java/com/vt/valuetogether/domain/checklist/entity/Checklist.java
  src/main/java/com/vt/valuetogether/domain/checklist/repository/ChecklistRepository.java
  src/main/java/com/vt/valuetogether/domain/checklist/service/ChecklistService.java
  src/main/resources/application-test.yml
  src/test/java/com/vt/valuetogether/domain/BaseMvcTest.java
  src/test/java/com/vt/valuetogether/domain/checklist/controller/ChecklistControllerTest.java
  src/test/java/com/vt/valuetogether/domain/checklist/repository/ChecklistRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/checklist/service/ChecklistServiceTest.java
  src/test/java/com/vt/valuetogether/test/ChecklistTest.java
Labels: feat

#32 make application-oauth.yml 추가
  .github/workflows/check.yml
  .github/workflows/gradle.yml
Labels: feat

#30 Feature/oath2
  .gitignore
  build.gradle
  src/main/java/com/vt/valuetogether/domain/oauth/OAuth2Attributes.java
  src/main/java/com/vt/valuetogether/domain/oauth/dto/OAuth2UserProfile.java
  src/main/java/com/vt/valuetogether/domain/oauth/exception/OAuth2ProviderInvalidException.java
  src/main/java/com/vt/valuetogether/domain/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/vt/valuetogether/domain/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/vt/valuetogether/domain/oauth/service/OAuth2Service.java
  src/main/java/com/vt/valuetogether/domain/user/entity/Provider.java
  src/main/java/com/vt/valuetogether/domain/user/entity/User.java
  src/main/java/com/vt/valuetogether/domain/user/repository/UserRepository.java
  src/main/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/vt/valuetogether/global/config/WebSecurityConfig.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/resources/application.yml
Labels: feat, refactor, chore

#34 [#21] Chore: yml group / include 추가
  src/main/resources/application.yml
Labels: chore

#35 Feat/add auth
  build.gradle
  src/main/java/com/vt/valuetogether/domain/user/dto/request/UserLocalLoginReq.java
  src/main/java/com/vt/valuetogether/domain/user/dto/response/UserLocalLoginRes.java
  src/main/java/com/vt/valuetogether/global/config/WebSecurityConfig.java
  src/main/java/com/vt/valuetogether/global/exception/ExceptionHandlerFilter.java
  src/main/java/com/vt/valuetogether/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/vt/valuetogether/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/vt/valuetogether/global/jwt/JwtUtil.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/redis/RedisConfig.java
  src/main/java/com/vt/valuetogether/global/redis/RedisUtil.java
  src/main/java/com/vt/valuetogether/global/security/UserDetailsImpl.java
  src/main/java/com/vt/valuetogether/global/security/UserDetailsServiceImpl.java
  src/main/java/com/vt/valuetogether/global/validator/TokenValidator.java
  src/main/java/com/vt/valuetogether/global/validator/UserValidator.java
  src/main/resources/application.yml
Labels: feat

#36 checklist 수정 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/checklist/controller/ChecklistController.java
  src/main/java/com/vt/valuetogether/domain/checklist/dto/request/ChecklistUpdateReq.java
  src/main/java/com/vt/valuetogether/domain/checklist/dto/response/ChecklistUpdateRes.java
  src/main/java/com/vt/valuetogether/domain/checklist/repository/ChecklistRepository.java
  src/main/java/com/vt/valuetogether/domain/checklist/service/ChecklistService.java
  src/main/java/com/vt/valuetogether/domain/model/BaseEntity.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/ChecklistValidator.java
  src/test/java/com/vt/valuetogether/domain/checklist/controller/ChecklistControllerTest.java
  src/test/java/com/vt/valuetogether/domain/checklist/repository/ChecklistRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/checklist/service/ChecklistServiceTest.java
Labels: feat

#40 sample api를 삭제합니다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/sample/controller/SampleController.java
  src/main/java/com/vt/valuetogether/domain/sample/dto/request/SampleSaveReq.java
  src/main/java/com/vt/valuetogether/domain/sample/dto/response/SampleGetRes.java
  src/main/java/com/vt/valuetogether/domain/sample/dto/response/SampleGetResList.java
  src/main/java/com/vt/valuetogether/domain/sample/dto/response/SampleSaveRes.java
  src/main/java/com/vt/valuetogether/domain/sample/entity/SampleEntity.java
  src/main/java/com/vt/valuetogether/domain/sample/repository/SampleRepository.java
  src/main/java/com/vt/valuetogether/domain/sample/servce/SampleService.java
  src/test/java/com/vt/valuetogether/domain/sample/controller/SampleControllerTest.java
Labels: clean

#42 restdocs에 errorcode 추가
  src/docs/asciidoc/index.adoc
Labels: docs

#44 checklist service interface 분리
  src/main/java/com/vt/valuetogether/domain/checklist/service/ChecklistService.java
  src/main/java/com/vt/valuetogether/domain/checklist/service/ChecklistServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/checklist/service/ChecklistServiceImplTest.java
Labels: refactor

#48 task 저장 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/task/controller/TaskController.java
  src/main/java/com/vt/valuetogether/domain/task/dto/request/TaskSaveReq.java
  src/main/java/com/vt/valuetogether/domain/task/dto/response/TaskSaveRes.java
  src/main/java/com/vt/valuetogether/domain/task/entity/Task.java
  src/main/java/com/vt/valuetogether/domain/task/repository/TaskRepository.java
  src/main/java/com/vt/valuetogether/domain/task/service/TaskService.java
  src/main/java/com/vt/valuetogether/domain/task/service/TaskServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/task/service/impl/TaskServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/TaskValidator.java
  src/test/java/com/vt/valuetogether/domain/task/controller/TaskControllerTest.java
  src/test/java/com/vt/valuetogether/domain/task/repository/TaskRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/task/service/impl/TaskServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/TaskTest.java
Labels: feat

#49 task 수정 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/task/controller/TaskController.java
  src/main/java/com/vt/valuetogether/domain/task/dto/request/TaskUpdateReq.java
  src/main/java/com/vt/valuetogether/domain/task/dto/response/TaskUpdateRes.java
  src/main/java/com/vt/valuetogether/domain/task/repository/TaskRepository.java
  src/main/java/com/vt/valuetogether/domain/task/service/TaskService.java
  src/main/java/com/vt/valuetogether/domain/task/service/impl/TaskServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/TaskValidator.java
  src/test/java/com/vt/valuetogether/domain/checklist/service/ChecklistServiceImplTest.java
  src/test/java/com/vt/valuetogether/domain/task/controller/TaskControllerTest.java
  src/test/java/com/vt/valuetogether/domain/task/repository/TaskRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/task/service/impl/TaskServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/ChecklistTest.java
  src/test/java/com/vt/valuetogether/test/TaskTest.java
Labels: feat

#50 task 삭제 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/task/controller/TaskController.java
  src/main/java/com/vt/valuetogether/domain/task/dto/request/TaskDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/task/dto/response/TaskDeleteRes.java
  src/main/java/com/vt/valuetogether/domain/task/repository/TaskRepository.java
  src/main/java/com/vt/valuetogether/domain/task/service/TaskService.java
  src/main/java/com/vt/valuetogether/domain/task/service/impl/TaskServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/checklist/service/ChecklistServiceImplTest.java
  src/test/java/com/vt/valuetogether/domain/task/controller/TaskControllerTest.java
  src/test/java/com/vt/valuetogether/domain/task/repository/TaskRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/task/service/impl/TaskServiceImplTest.java
Labels: feat

#26 팀 생성 기능 추가
  src/main/java/com/vt/valuetogether/domain/model/BaseEntity.java
  src/main/java/com/vt/valuetogether/domain/team/controller/TeamController.java
  src/main/java/com/vt/valuetogether/domain/team/dto/reponse/TeamCreateRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/reponse/TeamDeleteRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/request/TeamCreateReq.java
  src/main/java/com/vt/valuetogether/domain/team/dto/request/TeamDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/team/entity/Role.java
  src/main/java/com/vt/valuetogether/domain/team/entity/Team.java
  src/main/java/com/vt/valuetogether/domain/team/entity/TeamRole.java
  src/main/java/com/vt/valuetogether/domain/team/repository/TeamRepository.java
  src/main/java/com/vt/valuetogether/domain/team/repository/TeamRoleRepository.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamService.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/TeamValidator.java
  src/main/java/com/vt/valuetogether/global/validator/UserValidator.java
Labels: feat

#58 프로필 수정 기능 추가
  src/main/java/com/vt/valuetogether/domain/user/controller/UserController.java
  src/main/java/com/vt/valuetogether/domain/user/dto/request/UserCheckDuplicateUsernameReq.java
  src/main/java/com/vt/valuetogether/domain/user/dto/request/UserUpdateProfileReq.java
  src/main/java/com/vt/valuetogether/domain/user/dto/request/UserVerifyPasswordReq.java
  src/main/java/com/vt/valuetogether/domain/user/dto/response/UserCheckDuplicateUsernameRes.java
  src/main/java/com/vt/valuetogether/domain/user/dto/response/UserUpdateProfileRes.java
  src/main/java/com/vt/valuetogether/domain/user/dto/response/UserVerifyPasswordRes.java
  src/main/java/com/vt/valuetogether/domain/user/entity/User.java
  src/main/java/com/vt/valuetogether/domain/user/repository/UserRepository.java
  src/main/java/com/vt/valuetogether/domain/user/service/UserService.java
  src/main/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/S3Validator.java
  src/main/java/com/vt/valuetogether/global/validator/UserValidator.java
  src/main/java/com/vt/valuetogether/infra/s3/S3Util.java
  src/main/resources/application.yml
  src/main/resources/images/image1.jpg
  src/test/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/UserTest.java
Labels: feat

#64 Fix/edit redis auth
  src/main/java/com/vt/valuetogether/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/vt/valuetogether/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/vt/valuetogether/global/redis/RedisUtil.java
  src/main/java/com/vt/valuetogether/global/validator/TokenValidator.java
Labels: fix

#63 팀 삭제 / 편집 api 구현 및 버그 수정
  src/main/java/com/vt/valuetogether/domain/team/controller/TeamController.java
  src/main/java/com/vt/valuetogether/domain/team/dto/reponse/TeamEditRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/request/TeamEditReq.java
  src/main/java/com/vt/valuetogether/domain/team/entity/Team.java
  src/main/java/com/vt/valuetogether/domain/team/entity/TeamRole.java
  src/main/java/com/vt/valuetogether/domain/team/repository/TeamRoleRepository.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamService.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/TeamRoleValidator.java
  src/main/java/com/vt/valuetogether/global/validator/TeamValidator.java
Labels: feat, fix

#65 card 저장 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/card/controller/CardController.java
  src/main/java/com/vt/valuetogether/domain/card/dto/request/CardSaveReq.java
  src/main/java/com/vt/valuetogether/domain/card/dto/response/CardSaveRes.java
  src/main/java/com/vt/valuetogether/domain/card/entity/Card.java
  src/main/java/com/vt/valuetogether/domain/card/repository/CardRepository.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardService.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImpl.java
  src/main/java/com/vt/valuetogether/infra/s3/S3Util.java
  src/test/java/com/vt/valuetogether/domain/card/controller/CardControllerTest.java
  src/test/java/com/vt/valuetogether/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/CardTest.java
Labels: feat

#66 card 수정 api 추가
  .gitignore
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/card/controller/CardController.java
  src/main/java/com/vt/valuetogether/domain/card/dto/request/CardUpdateReq.java
  src/main/java/com/vt/valuetogether/domain/card/dto/response/CardUpdateRes.java
  src/main/java/com/vt/valuetogether/domain/card/entity/Card.java
  src/main/java/com/vt/valuetogether/domain/card/repository/CardRepository.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardService.java
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/CardValidator.java
  src/test/java/com/vt/valuetogether/domain/card/controller/CardControllerTest.java
  src/test/java/com/vt/valuetogether/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/CardTest.java
Labels: feat

#67 Feature/oauth2
  src/main/java/com/vt/valuetogether/domain/oauth/OAuth2Attributes.java
  src/main/java/com/vt/valuetogether/domain/oauth/constant/OAuth2Constant.java
  src/main/java/com/vt/valuetogether/domain/oauth/dto/request/OAuth2LoginReq.java
  src/main/java/com/vt/valuetogether/domain/oauth/dto/response/OAuth2LoginRes.java
  src/main/java/com/vt/valuetogether/domain/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/vt/valuetogether/domain/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/vt/valuetogether/domain/oauth/service/OAuth2Service.java
  src/main/java/com/vt/valuetogether/domain/user/entity/User.java
  src/main/java/com/vt/valuetogether/domain/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: feat, refactor

#70 checklist에 card 추가
  src/main/java/com/vt/valuetogether/domain/checklist/dto/request/ChecklistSaveReq.java
  src/main/java/com/vt/valuetogether/domain/checklist/entity/Checklist.java
  src/main/java/com/vt/valuetogether/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/checklist/repository/ChecklistRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/checklist/service/ChecklistServiceImplTest.java
  src/test/java/com/vt/valuetogether/domain/task/repository/TaskRepositoryTest.java
  src/test/java/com/vt/valuetogether/test/ChecklistTest.java
Labels: feat

#71 card 삭제 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/card/controller/CardController.java
  src/main/java/com/vt/valuetogether/domain/card/dto/request/CardDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/card/dto/response/CardDeleteRes.java
  src/main/java/com/vt/valuetogether/domain/card/repository/CardRepository.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardService.java
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/card/controller/CardControllerTest.java
  src/test/java/com/vt/valuetogether/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImplTest.java
Labels: feat

#74 card 단건 조회 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/card/controller/CardController.java
  src/main/java/com/vt/valuetogether/domain/card/dto/response/CardGetRes.java
  src/main/java/com/vt/valuetogether/domain/card/entity/Card.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardService.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/checklist/dto/response/ChecklistGetRes.java
  src/main/java/com/vt/valuetogether/domain/checklist/entity/Checklist.java
  src/main/java/com/vt/valuetogether/domain/task/dto/response/TaskGetRes.java
  src/test/java/com/vt/valuetogether/domain/card/controller/CardControllerTest.java
  src/test/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/CardTest.java
Labels: feat

#76 Feature/add logout
  src/main/java/com/vt/valuetogether/domain/user/dto/response/UserLogoutRes.java
  src/main/java/com/vt/valuetogether/global/config/WebSecurityConfig.java
  src/main/java/com/vt/valuetogether/global/exception/ExceptionHandlerFilter.java
  src/main/java/com/vt/valuetogether/global/jwt/JwtUtil.java
  src/main/java/com/vt/valuetogether/global/security/LogoutHandlerImpl.java
  src/main/java/com/vt/valuetogether/global/security/LogoutSuccessHandlerImpl.java
Labels: feat

#80 Feature/card seq
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/card/controller/CardController.java
  src/main/java/com/vt/valuetogether/domain/card/dto/request/CardChangeSequenceReq.java
  src/main/java/com/vt/valuetogether/domain/card/dto/response/CardChangeSequenceRes.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardService.java
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/card/controller/CardControllerTest.java
  src/test/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImplTest.java
Labels: feat, test, docs

#78 프로필 조회 api, 테스트 코드 추가
  src/main/java/com/vt/valuetogether/domain/user/controller/UserController.java
  src/main/java/com/vt/valuetogether/domain/user/dto/request/UserUpdateProfileReq.java
  src/main/java/com/vt/valuetogether/domain/user/dto/request/UserVerifyPasswordReq.java
  src/main/java/com/vt/valuetogether/domain/user/dto/response/UserGetProfileRes.java
  src/main/java/com/vt/valuetogether/domain/user/service/UserService.java
  src/main/java/com/vt/valuetogether/domain/user/service/UserServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/vt/valuetogether/global/config/WebSecurityConfig.java
  src/main/java/com/vt/valuetogether/global/validator/UserValidator.java
  src/main/java/com/vt/valuetogether/infra/mail/MailUtil.java
  src/test/java/com/vt/valuetogether/domain/BaseMvcTest.java
  src/test/java/com/vt/valuetogether/domain/user/controller/UserControllerTest.java
  src/test/java/com/vt/valuetogether/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImplTest.java
  src/test/java/com/vt/valuetogether/global/MockSpringSecurityFilter.java
Labels: feat, test

#83 card 조회 시 sequence 조회 추가
  src/main/java/com/vt/valuetogether/domain/card/dto/response/CardGetRes.java
Labels: fix

#86 댓글 저장 api 추가
  src/main/java/com/vt/valuetogether/domain/comment/controller/CommentController.java
  src/main/java/com/vt/valuetogether/domain/comment/dto/request/CommentSaveReq.java
  src/main/java/com/vt/valuetogether/domain/comment/dto/response/CommentSaveRes.java
  src/main/java/com/vt/valuetogether/domain/comment/entity/Comment.java
  src/main/java/com/vt/valuetogether/domain/comment/repository/CommentRepository.java
  src/main/java/com/vt/valuetogether/domain/comment/service/CommentService.java
  src/main/java/com/vt/valuetogether/domain/comment/service/CommentServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/comment/service/impl/CommentServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/BaseMvcTest.java
  src/test/java/com/vt/valuetogether/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/vt/valuetogether/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/comment/service/impl/CommentServiceImplTest.java
  src/test/java/com/vt/valuetogether/domain/user/controller/UserControllerTest.java
  src/test/java/com/vt/valuetogether/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/vt/valuetogether/test/CommentTest.java
Labels: feat

#84 팀 멤버 초대 기능 추가 및 버그 수정
  src/main/java/com/vt/valuetogether/domain/team/controller/TeamController.java
  src/main/java/com/vt/valuetogether/domain/team/dto/reponse/TeamMemberInviteRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/request/TeamMemberInviteReq.java
  src/main/java/com/vt/valuetogether/domain/team/entity/Team.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamService.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/user/entity/InviteCode.java
  src/main/java/com/vt/valuetogether/domain/user/repository/InviteRepository.java
  src/main/java/com/vt/valuetogether/domain/user/repository/UserRepository.java
  src/main/java/com/vt/valuetogether/domain/user/service/InviteCodeService.java
  src/main/java/com/vt/valuetogether/domain/user/service/impl/InviteCodeServiceImpl.java
  src/main/java/com/vt/valuetogether/global/config/WebSecurityConfig.java
  src/main/java/com/vt/valuetogether/global/validator/TeamValidator.java
  src/main/java/com/vt/valuetogether/infra/mail/MailUtil.java
Labels: feat, fix

#89 card sequence 재정렬 스케줄링 추가
  src/main/java/com/vt/valuetogether/domain/card/repository/CardRepository.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardSchedulingService.java
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardSchedulingServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/checklist/entity/Checklist.java
  src/test/java/com/vt/valuetogether/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/vt/valuetogether/test/CardTest.java
Labels: feat

#88 팀 조회 API 추가
  src/main/java/com/vt/valuetogether/domain/team/controller/TeamController.java
  src/main/java/com/vt/valuetogether/domain/team/dto/reponse/TeamGetRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/reponse/TeamMemberGetRes.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamService.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/TeamRoleValidator.java
Labels: feat

#94 팀 멤버 삭제 API 추가
  src/main/java/com/vt/valuetogether/domain/team/controller/TeamController.java
  src/main/java/com/vt/valuetogether/domain/team/dto/reponse/TeamMemberDeleteRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/request/TeamMemberDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamService.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/TeamRoleValidator.java
Labels: feat

#96 category save api 추가
  src/main/java/com/vt/valuetogether/domain/category/controller/CategoryController.java
  src/main/java/com/vt/valuetogether/domain/category/dto/request/CategorySaveReq.java
  src/main/java/com/vt/valuetogether/domain/category/dto/response/CategorySaveRes.java
  src/main/java/com/vt/valuetogether/domain/category/entity/Category.java
  src/main/java/com/vt/valuetogether/domain/category/repository/CategoryRepository.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategoryService.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategoryServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImpl.java
Labels: feat

#101 카테고리 삭제 API 구현
  src/main/java/com/vt/valuetogether/domain/category/controller/CategoryController.java
  src/main/java/com/vt/valuetogether/domain/category/dto/request/CategoryDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/category/dto/response/CategoryDeleteRes.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategoryService.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImpl.java
Labels: feat

#102 save category 테스트코드 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/global/validator/TeamRoleValidator.java
  src/test/java/com/vt/valuetogether/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/vt/valuetogether/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/CategoryTest.java
  src/test/java/com/vt/valuetogether/test/TeamTest.java
Labels: feat

#93 Feature/add worker api
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/card/entity/Card.java
  src/main/java/com/vt/valuetogether/domain/worker/controller/WorkerController.java
  src/main/java/com/vt/valuetogether/domain/worker/dto/request/WorkerAddReq.java
  src/main/java/com/vt/valuetogether/domain/worker/dto/request/WorkerDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/worker/dto/response/WorkerAddRes.java
  src/main/java/com/vt/valuetogether/domain/worker/dto/response/WorkerDeleteRes.java
  src/main/java/com/vt/valuetogether/domain/worker/entity/Worker.java
  src/main/java/com/vt/valuetogether/domain/worker/entity/WorkerPK.java
  src/main/java/com/vt/valuetogether/domain/worker/repository/WorkerRepository.java
  src/main/java/com/vt/valuetogether/domain/worker/service/WorkerService.java
  src/main/java/com/vt/valuetogether/domain/worker/service/WorkerServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/worker/service/impl/WorkerServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/WorkerValidator.java
  src/test/java/com/vt/valuetogether/domain/worker/controller/WorkerControllerTest.java
  src/test/java/com/vt/valuetogether/domain/worker/repository/WorkerRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/worker/service/WorkerServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/WorkerTest.java
Labels: feat, test

#105 team validator 추가
  src/main/java/com/vt/valuetogether/domain/card/controller/CardController.java
  src/main/java/com/vt/valuetogether/domain/card/dto/request/CardChangeSequenceReq.java
  src/main/java/com/vt/valuetogether/domain/card/dto/request/CardDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/card/dto/request/CardSaveReq.java
  src/main/java/com/vt/valuetogether/domain/card/dto/request/CardUpdateReq.java
  src/main/java/com/vt/valuetogether/domain/card/entity/Card.java
  src/main/java/com/vt/valuetogether/domain/card/repository/CardRepository.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardService.java
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardSchedulingServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/category/dto/request/CategoryDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/category/dto/request/CategoryEditReq.java
  src/main/java/com/vt/valuetogether/domain/category/dto/request/CategorySaveReq.java
  src/main/java/com/vt/valuetogether/domain/team/entity/Team.java
  src/test/java/com/vt/valuetogether/domain/card/controller/CardControllerTest.java
  src/test/java/com/vt/valuetogether/domain/card/repository/CardRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImplTest.java
  src/test/java/com/vt/valuetogether/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/checklist/repository/ChecklistRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/task/repository/TaskRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/worker/repository/WorkerRepositoryTest.java
  src/test/java/com/vt/valuetogether/test/CardTest.java
  src/test/java/com/vt/valuetogether/test/TeamRoleTest.java
Labels: fix, clean

#108 category sequence 변경 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/category/controller/CategoryController.java
  src/main/java/com/vt/valuetogether/domain/category/dto/request/CategoryChangeSequenceReq.java
  src/main/java/com/vt/valuetogether/domain/category/dto/response/CategoryChangeSequenceRes.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategoryService.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImplTest.java
Labels: feat

#110 Fix/catch expired token
  src/main/java/com/vt/valuetogether/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/vt/valuetogether/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/vt/valuetogether/global/jwt/JwtUtil.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/redis/RedisUtil.java
  src/main/java/com/vt/valuetogether/global/security/LogoutHandlerImpl.java
  src/main/java/com/vt/valuetogether/global/validator/TokenValidator.java
Labels: feat, refactor, fix

#111 [#103] Fix: OAuth2 버그 개선 (기존 사용자 username이 램덤으로 할당 된 버그 개선)
  src/main/java/com/vt/valuetogether/domain/oauth/OAuth2Attributes.java
  src/main/java/com/vt/valuetogether/domain/oauth/dto/request/OAuth2LoginReq.java
  src/main/java/com/vt/valuetogether/domain/oauth/service/OAuth2Service.java
Labels: fix

#115 Fix/change redis key
  src/main/java/com/vt/valuetogether/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/vt/valuetogether/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/vt/valuetogether/global/redis/RedisUtil.java
  src/main/java/com/vt/valuetogether/global/security/LogoutHandlerImpl.java
  src/main/java/com/vt/valuetogether/global/validator/TokenValidator.java
Labels: fix

#113 카테코리 전체 조회 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/card/dto/response/CardInnerCategoryRes.java
  src/main/java/com/vt/valuetogether/domain/category/controller/CategoryController.java
  src/main/java/com/vt/valuetogether/domain/category/dto/response/CategoryGetRes.java
  src/main/java/com/vt/valuetogether/domain/category/dto/response/CategoryGetResList.java
  src/main/java/com/vt/valuetogether/domain/category/entity/Category.java
  src/main/java/com/vt/valuetogether/domain/category/repository/CategoryRepository.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategoryService.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategoryServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/worker/dto/response/WorkerGetRes.java
  src/test/java/com/vt/valuetogether/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/vt/valuetogether/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/CategoryTest.java
Labels: feat

#116 댓글 삭제 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/comment/controller/CommentController.java
  src/main/java/com/vt/valuetogether/domain/comment/dto/request/CommentDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/comment/dto/response/CommentDeleteRes.java
  src/main/java/com/vt/valuetogether/domain/comment/repository/CommentRepository.java
  src/main/java/com/vt/valuetogether/domain/comment/service/CommentService.java
  src/main/java/com/vt/valuetogether/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/CommentValidator.java
  src/test/java/com/vt/valuetogether/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/vt/valuetogether/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/comment/service/impl/CommentServiceImplTest.java
  src/test/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/CommentTest.java
Labels: feat, test

#119 card 조회 시 담당자, 댓글 리스트 추가
  src/main/java/com/vt/valuetogether/domain/card/dto/response/CardGetRes.java
  src/main/java/com/vt/valuetogether/domain/card/entity/Card.java
  src/main/java/com/vt/valuetogether/domain/card/service/CardServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/comment/dto/response/CommentGetRes.java
  src/test/java/com/vt/valuetogether/domain/card/controller/CardControllerTest.java
Labels: feat

#122 댓글 수정 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/comment/controller/CommentController.java
  src/main/java/com/vt/valuetogether/domain/comment/dto/request/CommentUpdateReq.java
  src/main/java/com/vt/valuetogether/domain/comment/dto/response/CommentUpdateRes.java
  src/main/java/com/vt/valuetogether/domain/comment/service/CommentService.java
  src/main/java/com/vt/valuetogether/domain/comment/service/impl/CommentServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/vt/valuetogether/domain/comment/service/impl/CommentServiceImplTest.java
  src/test/java/com/vt/valuetogether/domain/user/controller/UserControllerTest.java
  src/test/java/com/vt/valuetogether/test/CommentTest.java
Labels: feat

#124 category sequence 재정렬 스케줄링 추가
  src/main/java/com/vt/valuetogether/domain/category/repository/CategoryRepository.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategorySchedulingService.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategorySchedulingServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/vt/valuetogether/test/CategoryTest.java
Labels: feat

#125 프로필 기본 이미지 설정
  src/main/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImpl.java
Labels: chore

#127 Feature/연관 관계
  src/main/java/com/vt/valuetogether/domain/card/entity/Card.java
  src/main/java/com/vt/valuetogether/domain/category/entity/Category.java
  src/main/java/com/vt/valuetogether/domain/checklist/entity/Checklist.java
  src/main/java/com/vt/valuetogether/domain/comment/entity/Comment.java
  src/main/java/com/vt/valuetogether/domain/team/entity/TeamRole.java
  src/main/java/com/vt/valuetogether/domain/worker/entity/Worker.java
Labels: feat

#130 category 삭제 스케줄러 추가
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardSchedulingServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/category/repository/CategoryRepository.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategorySchedulingService.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategorySchedulingServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/category/repository/CategoryRepositoryTest.java
Labels: feat

#131 Email 관련 테스트 코드 추가
  src/test/java/com/vt/valuetogether/domain/user/service/impl/EmailAuthServiceImplTest.java
  src/test/java/com/vt/valuetogether/infra/mail/MailUtilTest.java
  src/test/java/com/vt/valuetogether/test/EmailAuthTest.java
Labels: test

#133 username 중복 검사 api 오류 수정
  src/main/java/com/vt/valuetogether/domain/user/controller/UserController.java
Labels: fix

#134 deleted 상태가 아닌 카테고리만 조회
  src/main/java/com/vt/valuetogether/domain/category/dto/response/CategoryGetRes.java
  src/main/java/com/vt/valuetogether/domain/category/repository/CategoryRepository.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/vt/valuetogether/domain/category/repository/CategoryRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImplTest.java
Labels: fix

#136 카드, 카테고리 재정렬 시 null check 추가
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardSchedulingServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategorySchedulingServiceImpl.java
Labels: fix
