Repository yejin-kingdom/value-together, pull requests merged in 2024-01, with the labels that each got.

#138 카테고리 재정렬 시 전체조회 로직 수정
  src/main/java/com/vt/valuetogether/domain/category/repository/CategoryRepository.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategorySchedulingServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/category/repository/CategoryRepositoryTest.java
Labels: fix

#140 restdocs 문서 수정
  src/docs/asciidoc/index.adoc
Labels: docs

#154 email link에 yml 변수 주입
  src/main/java/com/vt/valuetogether/infra/mail/MailUtil.java
Labels: fix

#155 Test/team get
  src/docs/asciidoc/index.adoc
  src/test/java/com/vt/valuetogether/domain/team/controller/TeamControllerTest.java
  src/test/java/com/vt/valuetogether/domain/team/repository/TeamRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImplTest.java
Labels: test, docs

#160 Test/team delete
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/team/repository/TeamRepository.java
  src/test/java/com/vt/valuetogether/domain/team/controller/TeamControllerTest.java
  src/test/java/com/vt/valuetogether/domain/team/repository/TeamRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImplTest.java
Labels: refactor, test, docs

#161 Chore/change http method sort
  src/main/java/com/vt/valuetogether/domain/card/controller/CardController.java
  src/main/java/com/vt/valuetogether/domain/card/service/impl/CardServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/category/controller/CategoryController.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/user/controller/UserController.java
  src/main/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImpl.java
Labels: chore

#159 Worker, TemRole entity 연관관계 수정
  src/main/java/com/vt/valuetogether/domain/card/service/CardServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategoryServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/team/entity/TeamRole.java
  src/main/java/com/vt/valuetogether/domain/team/repository/TeamRoleRepository.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/worker/controller/WorkerController.java
  src/main/java/com/vt/valuetogether/domain/worker/dto/request/WorkerAddReq.java
  src/main/java/com/vt/valuetogether/domain/worker/dto/request/WorkerDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/worker/entity/Worker.java
  src/main/java/com/vt/valuetogether/domain/worker/entity/WorkerPK.java
  src/main/java/com/vt/valuetogether/domain/worker/repository/WorkerRepository.java
  src/main/java/com/vt/valuetogether/domain/worker/service/impl/WorkerServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/TeamRoleValidator.java
  src/test/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImplTest.java
  src/test/java/com/vt/valuetogether/domain/worker/controller/WorkerControllerTest.java
  src/test/java/com/vt/valuetogether/domain/worker/repository/WorkerRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/worker/service/WorkerServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/TeamRoleTest.java
  src/test/java/com/vt/valuetogether/test/WorkerTest.java
Labels: fix

#162 Comment, TemRole entity 연관관계 수정
  src/main/java/com/vt/valuetogether/domain/card/service/CardServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/comment/entity/Comment.java
  src/main/java/com/vt/valuetogether/domain/comment/service/impl/CommentServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/vt/valuetogether/domain/comment/service/impl/CommentServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/CommentTest.java
Labels: fix

#163 카테고리 softdelete 관련 api 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/category/controller/CategoryController.java
  src/main/java/com/vt/valuetogether/domain/category/dto/request/CategoryRestoreReq.java
  src/main/java/com/vt/valuetogether/domain/category/dto/response/CategoryRestoreRes.java
  src/main/java/com/vt/valuetogether/domain/category/service/CategoryService.java
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/CategoryValidator.java
  src/test/java/com/vt/valuetogether/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImplTest.java
Labels: feat, refactor, test

#164 Test/team invite
  src/docs/asciidoc/index.adoc
  src/test/java/com/vt/valuetogether/domain/team/controller/TeamControllerTest.java
  src/test/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImplTest.java
  src/test/java/com/vt/valuetogether/domain/user/repository/UserRepositoryTest.java
Labels: test, docs

#166 MailUtil 리팩토링
  src/main/java/com/vt/valuetogether/infra/mail/MailUtil.java
Labels: refactor

#167 팀 초대 시 멤버인지 확인 로직 추가
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
Labels: fix

#170 체크리스트 api 요청 시 팀의 멤버인지 확인 로직 추가
  src/main/java/com/vt/valuetogether/domain/checklist/controller/ChecklistController.java
  src/main/java/com/vt/valuetogether/domain/checklist/dto/request/ChecklistDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/checklist/dto/request/ChecklistSaveReq.java
  src/main/java/com/vt/valuetogether/domain/checklist/dto/request/ChecklistUpdateReq.java
  src/main/java/com/vt/valuetogether/domain/checklist/service/impl/ChecklistServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/checklist/controller/ChecklistControllerTest.java
  src/test/java/com/vt/valuetogether/domain/checklist/service/ChecklistServiceImplTest.java
Labels: fix

#171 할일 api 요청 시 팀의 멤버인지 확인 로직 추가
  src/main/java/com/vt/valuetogether/domain/task/controller/TaskController.java
  src/main/java/com/vt/valuetogether/domain/task/dto/request/TaskDeleteReq.java
  src/main/java/com/vt/valuetogether/domain/task/dto/request/TaskSaveReq.java
  src/main/java/com/vt/valuetogether/domain/task/dto/request/TaskUpdateReq.java
  src/main/java/com/vt/valuetogether/domain/task/service/impl/TaskServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/task/controller/TaskControllerTest.java
  src/test/java/com/vt/valuetogether/domain/task/service/impl/TaskServiceImplTest.java
Labels: fix

#172 Test/member delete
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/team/dto/request/TeamMemberDeleteReq.java
  src/test/java/com/vt/valuetogether/domain/team/controller/TeamControllerTest.java
  src/test/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImplTest.java
Labels: refactor, test, docs

#174 Refactor/user
  src/main/java/com/vt/valuetogether/domain/oauth/OAuth2Attributes.java
  src/main/java/com/vt/valuetogether/domain/oauth/exception/OAuth2ProviderInvalidException.java
  src/main/java/com/vt/valuetogether/domain/oauth/service/OAuth2Service.java
  src/main/java/com/vt/valuetogether/domain/team/controller/TeamController.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/user/controller/UserController.java
  src/main/java/com/vt/valuetogether/domain/user/entity/User.java
  src/main/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImpl.java
Labels: refactor

#176 aws keys 추가
  .github/workflows/gradle.yml
Labels: docs

#178 invite code service 테스트코드 추가
  src/test/java/com/vt/valuetogether/domain/user/service/impl/InviteCodeServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/InviteCodeTest.java
Labels: test

#179 팀 수정 테스트 코드 추가
  src/docs/asciidoc/index.adoc
  src/test/java/com/vt/valuetogether/domain/team/controller/TeamControllerTest.java
  src/test/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/TeamTest.java
Labels: refactor, test

#180 Refactor/backgound color regex
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/team/controller/TeamController.java
  src/main/java/com/vt/valuetogether/domain/team/dto/response/TeamCreateRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/response/TeamDeleteRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/response/TeamEditRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/response/TeamGetRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/response/TeamMemberDeleteRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/response/TeamMemberGetRes.java
  src/main/java/com/vt/valuetogether/domain/team/dto/response/TeamMemberInviteRes.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamService.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamServiceMapper.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
  src/main/java/com/vt/valuetogether/global/validator/TeamValidator.java
  src/test/java/com/vt/valuetogether/domain/team/controller/TeamControllerTest.java
  src/test/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/TeamTest.java
Labels: refactor, test, rename

#183 중복 이메일 체크
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/user/repository/UserRepository.java
  src/main/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/UserValidator.java
  src/test/java/com/vt/valuetogether/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/vt/valuetogether/test/UserTest.java
Labels: fix

#184 Docs/jacoco
  .gitignore
  build.gradle
Labels: docs

#185 Test/edit category
  src/docs/asciidoc/index.adoc
  src/test/java/com/vt/valuetogether/domain/category/controller/CategoryControllerTest.java
  src/test/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImplTest.java
Labels: test

#187 [#186] Fix: Team save 시 빠진 필드 추가
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
Labels: fix

#190 삭제된 카테고리 복구 시 sequence 값 수정
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategoryServiceImpl.java
Labels: fix

#192 팀 복구 기능 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/vt/valuetogether/domain/team/controller/TeamController.java
  src/main/java/com/vt/valuetogether/domain/team/dto/request/TeamRestoreReq.java
  src/main/java/com/vt/valuetogether/domain/team/dto/response/TeamRestoreRes.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamService.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
  src/main/java/com/vt/valuetogether/global/meta/ResultCode.java
  src/main/java/com/vt/valuetogether/global/validator/TeamRoleValidator.java
  src/main/java/com/vt/valuetogether/global/validator/TeamValidator.java
  src/test/java/com/vt/valuetogether/domain/team/controller/TeamControllerTest.java
  src/test/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImplTest.java
  src/test/java/com/vt/valuetogether/test/TeamTest.java
Labels: feat, test

#194 Team 전체 삭제 스케줄러 추가
  src/main/java/com/vt/valuetogether/domain/category/service/impl/CategorySchedulingServiceImpl.java
  src/main/java/com/vt/valuetogether/domain/team/entity/Team.java
  src/main/java/com/vt/valuetogether/domain/team/repository/TeamRepository.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamSchedulingService.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamSchedulingServiceImpl.java
  src/main/java/com/vt/valuetogether/global/validator/TeamValidator.java
  src/test/java/com/vt/valuetogether/domain/team/repository/TeamRepositoryTest.java
  src/test/java/com/vt/valuetogether/test/TeamTest.java
Labels: feat

#195 깃허브 readme 작성
  README.md
  image/ERD.png
  image/JacocoTest.png
Labels: docs

#196 OAuth2 로그인시 default image 적용
  src/main/java/com/vt/valuetogether/domain/oauth/OAuth2Attributes.java
  src/main/java/com/vt/valuetogether/domain/oauth/dto/request/OAuth2LoginReq.java
  src/main/java/com/vt/valuetogether/domain/oauth/service/OAuth2Service.java
Labels: fix

#200 global, infra 패키지 정리
  src/main/java/com/vt/valuetogether/global/jpa/AuditingConfig.java
  src/main/java/com/vt/valuetogether/global/security/WebSecurityConfig.java
  src/main/java/com/vt/valuetogether/infra/s3/S3Config.java
Labels: refactor

#199 [#197] Fix: inviteMember Response Dto 추가 및 변경
  src/main/java/com/vt/valuetogether/domain/team/controller/TeamController.java
  src/main/java/com/vt/valuetogether/domain/team/dto/response/TeamMemberConfirmEmailRes.java
  src/main/java/com/vt/valuetogether/domain/team/service/TeamService.java
  src/main/java/com/vt/valuetogether/domain/team/service/impl/TeamServiceImpl.java
Labels: refactor, fix

#202 username 제거
  src/main/java/com/vt/valuetogether/domain/user/controller/UserController.java
  src/main/java/com/vt/valuetogether/domain/user/dto/request/UserUpdateProfileReq.java
  src/main/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImpl.java
  src/test/java/com/vt/valuetogether/domain/user/controller/UserControllerTest.java
  src/test/java/com/vt/valuetogether/domain/user/service/impl/UserServiceImplTest.java
Labels: fix
